sudo: required
services:
   - docker

before_install:
   - docker build -t raveekirann/react-test -f ./client/Dockerfile.dev ./client

script:
   - docker run -e CI=true raveekirann/react-test npm test

after_success:
   - docker build -t raveekirann/multi-client ./client
   - docker build -t raveekirann/multi-nginx ./nginx
   - docker build -t raveekirann/multi-server ./server
   - docker build -t raveekirann/multi-worker ./worker
  
  
   # login to  the  docker CLI
   - echo  "$DOCKER_PASS" | docker  login  -u "$DOCKER_ID"  --password-stdin
   #take the images  and  push to  docker hub

   - docker push raveekirann/multi-client
   - docker push raveekirann/multi-nginx
   - docker push raveekirann/multi-server
   - docker push raveekirann/multi-worker
deploy:
   provider: elasticbeanstalk
   region: us-east-1
   app: multi-docker
   env: MultiDocker-env
   bucket_name: elasticbeanstalk-us-east-1-541573570611
   bucket_path: docker-multi
   on:
      branch: master
   access_key_id:  $AWS_ACCESS_KEY
   secret_access_key:
      secure: $AWS_SECRET_KEY